// State data for Nigeria, including states and their respective local government areas (LGAs)
export const nigeriaStates = {
  Abia: [
    "Aba North",
    "Aba South",
    "Arochukwu",
    "Bende",
    "Ikwuano",
    "Isiala Ngwa North",
    "Isiala Ngwa South",
    "Isuikwuato",
    "Obi Ngwa",
    "Ohafia",
    "Osisioma",
    "Ugwunagbo",
    "Ukwa East",
    "Ukwa West",
    "Umuahia North",
    "Umuahia South",
    "Umu Nneochi",
  ],

  Adamawa: [
    "Demsa",
    "Fufore",
    "Ganye",
    "Girei",
    "Gombi",
    "Guyuk",
    "Hong",
    "Jada",
    "Lamurde",
    "Madagali",
    "Maiha",
    "Mayo Belwa",
    "Michika",
    "Mubi North",
    "Mubi South",
    "Numan",
    "Shelleng",
    "Song",
    "Toungo",
    "Yola North",
    "Yola South",
  ],

  AkwaIbom: [
    "Abak",
    "Eastern Obolo",
    "Eket",
    "Esit Eket",
    "Essien Udim",
    "Etim Ekpo",
    "Etinan",
    "Ibeno",
    "Ibesikpo Asutan",
    "Ibiono Ibom",
    "Ika",
    "Ikono",
    "Ikot Abasi",
    "Ikot Ekpene",
    "Ini",
    "Itu",
    "Mbo",
    "Mkpat Enin",
    "Nsit Atai",
    "Nsit Ibom",
    "Nsit Ubium",
    "Obot Akara",
    "Okobo",
    "Onna",
    "Oron",
    "Oruk Anam",
    "Udung Uko",
    "Ukanafun",
    "Uruan",
    "Urue-Offong Oruko",
    "Uyo",
  ],

  Anambra: [
    "Aguata",
    "Anambra East",
    "Anambra West",
    "Anaocha",
    "Awka North",
    "Awka South",
    "Ayamelum",
    "Dunukofia",
    "Ekwusigo",
    "Idemili North",
    "Idemili South",
    "Ihiala",
    "Njikoka",
    "Nnewi North",
    "Nnewi South",
    "Ogbaru",
    "Onitsha North",
    "Onitsha South",
    "Orumba North",
    "Orumba South",
    "Oyi",
  ],

  Bauchi: [
    "Alkaleri",
    "Bauchi",
    "Bogoro",
    "Damban",
    "Darazo",
    "Dass",
    "Gamawa",
    "Ganjuwa",
    "Giade",
    "Itas Gadau",
    "Jama'are",
    "Katagum",
    "Kirfi",
    "Misau",
    "Ningi",
    "Shira",
    "Tafawa Balewa",
    "Toro",
    "Warji",
    "Zaki",
  ],

  Bayelsa: [
    "Brass",
    "Ekeremor",
    "Kolokuma Opokuma",
    "Nembe",
    "Ogbia",
    "Sagbama",
    "Southern Ijaw",
    "Yenagoa",
  ],

  Benue: [
    "Ado",
    "Agatu",
    "Apa",
    "Buruku",
    "Gboko",
    "Guma",
    "Gwer East",
    "Gwer West",
    "Katsina Ala",
    "Konshisha",
    "Kwande",
    "Logo",
    "Makurdi",
    "Obi",
    "Ogbadibo",
    "Ohimini",
    "Oju",
    "Okpokwu",
    "Otukpo",
    "Tarka",
    "Ukum",
    "Ushongo",
    "Vandeikya",
  ],

  Borno: [
    "Abadam",
    "Askira Uba",
    "Bama",
    "Bayo",
    "Biu",
    "Chibok",
    "Damboa",
    "Dikwa",
    "Gubio",
    "Guzamala",
    "Gwoza",
    "Hawul",
    "Jere",
    "Kaga",
    "Kala Balge",
    "Konduga",
    "Kukawa",
    "Kwaya Kusar",
    "Mafa",
    "Magumeri",
    "Maiduguri",
    "Marte",
    "Mobbar",
    "Monguno",
    "Ngala",
    "Nganzai",
    "Shani",
  ],

  CrossRiver: [
    "Abi",
    "Akamkpa",
    "Akpabuyo",
    "Bakassi",
    "Bekwarra",
    "Biase",
    "Boki",
    "Calabar Municipal",
    "Calabar South",
    "Etung",
    "Ikom",
    "Obanliku",
    "Obubra",
    "Obudu",
    "Odukpani",
    "Ogoja",
    "Yakuur",
    "Yala",
  ],

  Delta: [
    "Aniocha North",
    "Aniocha South",
    "Bomadi",
    "Burutu",
    "Ethiope East",
    "Ethiope West",
    "Ika North East",
    "Ika South",
    "Isoko North",
    "Isoko South",
    "Ndokwa East",
    "Ndokwa West",
    "Okpe",
    "Oshimili North",
    "Oshimili South",
    "Patani",
    "Sapele",
    "Udu",
    "Ughelli North",
    "Ughelli South",
    "Ukwuani",
    "Uvwie",
    "Warri North",
    "Warri South",
    "Warri South West",
  ],

  Edo: [
    "Akoko Edo",
    "Egor",
    "Esan Central",
    "Esan North East",
    "Esan South East",
    "Esan West",
    "Etsako Central",
    "Etsako East",
    "Etsako West",
    "Igueben",
    "Ikpoba Okha",
    "Oredo",
    "Orhionmwon",
    "Ovia North East",
    "Ovia South West",
    "Owan East",
    "Owan West",
    "Uhunmwonde",
  ],

  Ekiti: [
    "Ado Ekiti",
    "Efon",
    "Ekiti East",
    "Ekiti South West",
    "Ekiti West",
    "Emure",
    "Gbonyin",
    "Ido Osi",
    "Ijero",
    "Ikere",
    "Ikole",
    "Ilejemeje",
    "Irepodun Ifelodun",
    "Ise Orun",
    "Moba",
    "Oye",
  ],

  Enugu: [
    "Aninri",
    "Awgu",
    "Enugu East",
    "Enugu North",
    "Enugu South",
    "Ezeagu",
    "Igbo Etiti",
    "Igbo Eze North",
    "Igbo Eze South",
    "Isi Uzo",
    "Nkanu East",
    "Nkanu West",
    "Nsukka",
    "Oji River",
    "Udenu",
    "Udi",
    "Uzo Uwani",
  ],

  FCT: ["Abaji", "Abuja Municipal", "Bwari", "Gwagwalada", "Kuje", "Kwali"],

  Gombe: [
    "Akko",
    "Balanga",
    "Billiri",
    "Dukku",
    "Funakaye",
    "Gombe",
    "Kaltungo",
    "Kwami",
    "Nafada",
    "Shongom",
    "Yamaltu Deba",
  ],

  Imo: [
    "Aboh Mbaise",
    "Ahiazu Mbaise",
    "Ehime Mbano",
    "Ezinihitte",
    "Ideato North",
    "Ideato South",
    "Ihitte Uboma",
    "Ikeduru",
    "Isiala Mbano",
    "Isu",
    "Mbaitoli",
    "Ngor Okpala",
    "Njaba",
    "Nkwerre",
    "Nwangele",
    "Obowo",
    "Oguta",
    "Ohaji Egbema",
    "Okigwe",
    "Orlu",
    "Orsu",
    "Oru East",
    "Oru West",
    "Owerri Municipal",
    "Owerri North",
    "Owerri West",
    "Unuimo",
  ],

  Jigawa: [
    "Auyo",
    "Babura",
    "Biriniwa",
    "Birnin Kudu",
    "Buji",
    "Dutse",
    "Gagarawa",
    "Garki",
    "Gumel",
    "Guri",
    "Gwaram",
    "Gwiwa",
    "Hadejia",
    "Jahun",
    "Kafin Hausa",
    "Kazaure",
    "Kiri Kasama",
    "Kiyawa",
    "Maigatari",
    "Malam Madori",
    "Miga",
    "Ringim",
    "Roni",
    "Sule Tankarkar",
    "Taura",
    "Yankwashi",
  ],

  Kaduna: [
    "Birnin Gwari",
    "Chikun",
    "Giwa",
    "Igabi",
    "Ikara",
    "Jaba",
    "Jema'a",
    "Kachia",
    "Kaduna North",
    "Kaduna South",
    "Kagarko",
    "Kajuru",
    "Kaura",
    "Kauru",
    "Kubau",
    "Kudan",
    "Lere",
    "Makarfi",
    "Sabon Gari",
    "Sanga",
    "Soba",
    "Zangon Kataf",
    "Zaria",
  ],

  Kano: [
    "Ajingi",
    "Albasu",
    "Bagwai",
    "Bebeji",
    "Bichi",
    "Bunkure",
    "Dala",
    "Dambatta",
    "Dawakin Kudu",
    "Dawakin Tofa",
    "Doguwa",
    "Fagge",
    "Gabasawa",
    "Garko",
    "Garun Mallam",
    "Gaya",
    "Gezawa",
    "Gwale",
    "Gwarzo",
    "Kabo",
    "Kano Municipal",
    "Karaye",
    "Kibiya",
    "Kiru",
    "Kumbotso",
    "Kunchi",
    "Kura",
    "Madobi",
    "Makoda",
    "Minjibir",
    "Nasarawa",
    "Rano",
    "Rimin Gado",
    "Rogo",
    "Shanono",
    "Sumaila",
    "Takai",
    "Tarauni",
    "Tofa",
    "Tsanyawa",
    "Tudun Wada",
    "Ungogo",
    "Warawa",
    "Wudil",
  ],

  Kwara: [
    "Asa",
    "Baruten",
    "Edu",
    "Ekiti",
    "Ifelodun",
    "Ilorin East",
    "Ilorin South",
    "Ilorin West",
    "Irepodun",
    "Isin",
    "Kaiama",
    "Moro",
    "Offa",
    "Oke Ero",
    "Oyun",
    "Pategi",
  ],

  Lagos: [
    "Agege",
    "Ajeromi-Ifelodun",
    "Alimosho",
    "Amuwo-Odofin",
    "Apapa",
    "Badagry",
    "Epe",
    "Eti-Osa",
    "Ibeju-Lekki",
    "Ifako-Ijaiye",
    "Ikeja",
    "Ikorodu",
    "Kosofe",
    "Lagos Island",
    "Lagos Mainland",
    "Mushin",
    "Ojo",
    "Oshodi-Isolo",
    "Shomolu",
    "Surulere",
  ],

  Rivers: [
    "Port Harcourt",
    "Obio-Akpor",
    "Okrika",
    "Ogu-Bolo",
    "Eleme",
    "Tai",
    "Gokana",
    "Khana",
    "Oyigbo",
    "Opobo-Nkoro",
    "Andoni",
    "Bonny",
    "Degema",
    "Asari-Toru",
    "Akuku-Toru",
    "Abua-Odual",
    "Ahoada East",
    "Ahoada West",
    "Ogba-Egbema-Ndoni",
    "Emohua",
    "Ikwerre",
    "Etche",
    "Omuma",
  ],
  Katsina: [
    "Bakori",
    "Batagarawa",
    "Batsari",
    "Baure",
    "Bindawa",
    "Charanchi",
    "Dan Musa",
    "Dandume",
    "Danja",
    "Daura",
    "Dutsi",
    "Dutsin Ma",
    "Faskari",
    "Funtua",
    "Ingawa",
    "Jibia",
    "Kafur",
    "Kaita",
    "Kankara",
    "Kankia",
    "Katsina",
    "Kurfi",
    "Kusada",
    "Mai Adua",
    "Malumfashi",
    "Mani",
    "Mashi",
    "Matazu",
    "Musawa",
    "Rimi",
    "Sabuwa",
    "Safana",
    "Sandamu",
    "Zango",
  ],

  Kebbi: [
    "Aleiro",
    "Arewa Dandi",
    "Argungu",
    "Augie",
    "Bagudo",
    "Birnin Kebbi",
    "Bunza",
    "Dandi",
    "Fakai",
    "Gwandu",
    "Jega",
    "Kalgo",
    "Koko Besse",
    "Maiyama",
    "Ngaski",
    "Sakaba",
    "Shanga",
    "Suru",
    "Wasagu Danko",
    "Yauri",
    "Zuru",
  ],

  Kogi: [
    "Adavi",
    "Ajaokuta",
    "Ankpa",
    "Bassa",
    "Dekina",
    "Ibaji",
    "Idah",
    "Igalamela Odolu",
    "Ijumu",
    "Kabba Bunu",
    "Kogi",
    "Lokoja",
    "Mopa Muro",
    "Ofu",
    "Ogori Magongo",
    "Okehi",
    "Okene",
    "Olamaboro",
    "Omala",
    "Yagba East",
    "Yagba West",
  ],

  Nasarawa: [
    "Akwanga",
    "Awe",
    "Doma",
    "Karu",
    "Keana",
    "Keffi",
    "Kokona",
    "Lafia",
    "Nasarawa",
    "Nasarawa Egon",
    "Obi",
    "Toto",
    "Wamba",
  ],

  Niger: [
    "Agaie",
    "Agwara",
    "Bida",
    "Borgu",
    "Bosso",
    "Chanchaga",
    "Edati",
    "Gbako",
    "Gurara",
    "Katcha",
    "Kontagora",
    "Lapai",
    "Lavun",
    "Magama",
    "Mariga",
    "Mashegu",
    "Mokwa",
    "Muya",
    "Paikoro",
    "Rafi",
    "Rijau",
    "Shiroro",
    "Suleja",
    "Tafa",
    "Wushishi",
  ],

  Ogun: [
    "Abeokuta North",
    "Abeokuta South",
    "Ado Odo Ota",
    "Egbado North",
    "Egbado South",
    "Ewekoro",
    "Ifo",
    "Ijebu East",
    "Ijebu North",
    "Ijebu North East",
    "Ijebu Ode",
    "Ikenne",
    "Imeko Afon",
    "Ipokia",
    "Obafemi Owode",
    "Odeda",
    "Odogbolu",
    "Ogun Waterside",
    "Remo North",
    "Shagamu",
  ],

  Ondo: [
    "Akoko North East",
    "Akoko North West",
    "Akoko South Akure",
    "Akoko South West",
    "Akure North",
    "Akure South",
    "Ese Odo",
    "Idanre",
    "Ifedore",
    "Ilaje",
    "Ile Oluji Okeigbo",
    "Irele",
    "Odigbo",
    "Okitipupa",
    "Ondo East",
    "Ondo West",
    "Ose",
    "Owo",
  ],

  Osun: [
    "Aiyedade",
    "Aiyedire",
    "Atakumosa East",
    "Atakumosa West",
    "Boluwaduro",
    "Boripe",
    "Ede North",
    "Ede South",
    "Egbedore",
    "Ejigbo",
    "Ife Central",
    "Ife East",
    "Ife North",
    "Ife South",
    "Ifedayo",
    "Ifelodun",
    "Ila",
    "Ilesa East",
    "Ilesa West",
    "Irepodun",
    "Irewole",
    "Isokan",
    "Iwo",
    "Obokun",
    "Odo Otin",
    "Ola Oluwa",
    "Olorunda",
    "Oriade",
    "Orolu",
    "Osogbo",
  ],

  Oyo: [
    "Afijio",
    "Akinyele",
    "Atiba",
    "Atisbo",
    "Egbeda",
    "Ibadan North",
    "Ibadan North East",
    "Ibadan North West",
    "Ibadan South East",
    "Ibadan South West",
    "Ibarapa Central",
    "Ibarapa East",
    "Ibarapa North",
    "Ido",
    "Irepo",
    "Iseyin",
    "Itesiwaju",
    "Iwajowa",
    "Kajola",
    "Lagelu",
    "Ogbomosho North",
    "Ogbomosho South",
    "Ogo Oluwa",
    "Olorunsogo",
    "Oluyole",
    "Ona Ara",
    "Orelope",
    "Ori Ire",
    "Oyo East",
    "Oyo West",
    "Saki East",
    "Saki West",
    "Surulere",
  ],

  Plateau: [
    "Barkin Ladi",
    "Bassa",
    "Bokkos",
    "Jos East",
    "Jos North",
    "Jos South",
    "Kanam",
    "Kanke",
    "Langtang North",
    "Langtang South",
    "Mangu",
    "Mikang",
    "Pankshin",
    "Qua'an Pan",
    "Riyom",
    "Shendam",
    "Wase",
  ],

  Sokoto: [
    "Binji",
    "Bodinga",
    "Dange Shuni",
    "Gada",
    "Goronyo",
    "Gudu",
    "Gwadabawa",
    "Illela",
    "Isa",
    "Kebbe",
    "Kware",
    "Rabah",
    "Sabon Birni",
    "Shagari",
    "Silame",
    "Sokoto North",
    "Sokoto South",
    "Tambuwal",
    "Tangaza",
    "Tureta",
    "Wamako",
    "Wurno",
    "Yabo",
  ],

  Taraba: [
    "Ardo Kola",
    "Bali",
    "Donga",
    "Gashaka",
    "Gassol",
    "Ibi",
    "Jalingo",
    "Karim Lamido",
    "Kumi",
    "Lau",
    "Sardauna",
    "Takum",
    "Ussa",
    "Wukari",
    "Yorro",
    "Zing",
  ],

  Yobe: [
    "Bade",
    "Bursari",
    "Damaturu",
    "Fika",
    "Fune",
    "Geidam",
    "Gujba",
    "Gulani",
    "Jakusko",
    "Karasuwa",
    "Machina",
    "Nangere",
    "Nguru",
    "Potiskum",
    "Tarmuwa",
    "Yunusari",
    "Yusufari",
  ],

  Zamfara: [
    "Anka",
    "Bakura",
    "Birnin Magaji",
    "Bukkuyum",
    "Bungudu",
    "Gummi",
    "Gusau",
    "Kaura Namoda",
    "Maradun",
    "Maru",
    "Shinkafi",
    "Talata Mafara",
    "Tsafe",
    "Zurmi",
  ],
};

// Country data with ISO 3166-1 alpha-2 codes and country names
export const countries = [
    { id: 1, code: "AF", name: "Afghanistan" },
    { id: 2, code: "AL", name: "Albania" },
    { id: 3, code: "DZ", name: "Algeria" },
    { id: 4, code: "AD", name: "Andorra" },
    { id: 5, code: "AO", name: "Angola" },
    { id: 6, code: "AR", name: "Argentina" },
    { id: 7, code: "AM", name: "Armenia" },
    { id: 8, code: "AU", name: "Australia" },
    { id: 9, code: "AT", name: "Austria" },
    { id: 10, code: "AZ", name: "Azerbaijan" },
    { id: 11, code: "BS", name: "Bahamas" },
    { id: 12, code: "BH", name: "Bahrain" },
    { id: 13, code: "BD", name: "Bangladesh" },
    { id: 14, code: "BB", name: "Barbados" },
    { id: 15, code: "BY", name: "Belarus" },
    { id: 16, code: "BE", name: "Belgium" },
    { id: 17, code: "BZ", name: "Belize" },
    { id: 18, code: "BJ", name: "Benin" },
    { id: 19, code: "BT", name: "Bhutan" },
    { id: 20, code: "BO", name: "Bolivia" },
    { id: 21, code: "BA", name: "Bosnia and Herzegovina" },
    { id: 22, code: "BW", name: "Botswana" },
    { id: 23, code: "BR", name: "Brazil" },
    { id: 24, code: "BN", name: "Brunei" },
    { id: 25, code: "BG", name: "Bulgaria" },
    { id: 26, code: "BF", name: "Burkina Faso" },
    { id: 27, code: "BI", name: "Burundi" },
    { id: 28, code: "KH", name: "Cambodia" },
    { id: 29, code: "CM", name: "Cameroon" },
    { id: 30, code: "CA", name: "Canada" },
    { id: 31, code: "CV", name: "Cape Verde" },
    { id: 32, code: "CF", name: "Central African Republic" },
    { id: 33, code: "TD", name: "Chad" },
    { id: 34, code: "CL", name: "Chile" },
    { id: 35, code: "CN", name: "China" },
    { id: 36, code: "CO", name: "Colombia" },
    { id: 37, code: "KM", name: "Comoros" },
    { id: 38, code: "CG", name: "Congo" },
    { id: 39, code: "CR", name: "Costa Rica" },
    { id: 40, code: "HR", name: "Croatia" },
    { id: 41, code: "CU", name: "Cuba" },
    { id: 42, code: "CY", name: "Cyprus" },
    { id: 43, code: "CZ", name: "Czech Republic" },
    { id: 44, code: "DK", name: "Denmark" },
    { id: 45, code: "DJ", name: "Djibouti" },
    { id: 46, code: "DO", name: "Dominican Republic" },
    { id: 47, code: "EC", name: "Ecuador" },
    { id: 48, code: "EG", name: "Egypt" },
    { id: 49, code: "SV", name: "El Salvador" },
    { id: 50, code: "GQ", name: "Equatorial Guinea" },
    { id: 51, code: "ER", name: "Eritrea" },
    { id: 52, code: "EE", name: "Estonia" },
    { id: 53, code: "ET", name: "Ethiopia" },
    { id: 54, code: "FJ", name: "Fiji" },
    { id: 55, code: "FI", name: "Finland" },
    { id: 56, code: "FR", name: "France" },
    { id: 57, code: "GA", name: "Gabon" },
    { id: 58, code: "GM", name: "Gambia" },
    { id: 59, code: "GE", name: "Georgia" },
    { id: 60, code: "DE", name: "Germany" },
    { id: 61, code: "GH", name: "Ghana" },
    { id: 62, code: "GR", name: "Greece" },
    { id: 63, code: "GT", name: "Guatemala" },
    { id: 64, code: "GN", name: "Guinea" },
    { id: 65, code: "GW", name: "Guinea-Bissau" },
    { id: 66, code: "GY", name: "Guyana" },
    { id: 67, code: "HT", name: "Haiti" },
    { id: 68, code: "HN", name: "Honduras" },
    { id: 69, code: "HU", name: "Hungary" },
    { id: 70, code: "IS", name: "Iceland" },
    { id: 71, code: "IN", name: "India" },
    { id: 72, code: "ID", name: "Indonesia" },
    { id: 73, code: "IR", name: "Iran" },
    { id: 74, code: "IQ", name: "Iraq" },
    { id: 75, code: "IE", name: "Ireland" },
    { id: 76, code: "IL", name: "Israel" },
    { id: 77, code: "IT", name: "Italy" },
    { id: 78, code: "JM", name: "Jamaica" },
    { id: 79, code: "JP", name: "Japan" },
    { id: 80, code: "JO", name: "Jordan" },
    { id: 81, code: "KZ", name: "Kazakhstan" },
    { id: 82, code: "KE", name: "Kenya" },
    { id: 83, code: "KI", name: "Kiribati" },
    { id: 84, code: "KW", name: "Kuwait" },
    { id: 85, code: "KG", name: "Kyrgyzstan" },
    { id: 86, code: "LA", name: "Laos" },
    { id: 87, code: "LV", name: "Latvia" },
    { id: 88, code: "LB", name: "Lebanon" },
    { id: 89, code: "LS", name: "Lesotho" },
    { id: 90, code: "LR", name: "Liberia" },
    { id: 91, code: "LY", name: "Libya" },
    { id: 92, code: "LT", name: "Lithuania" },
    { id: 93, code: "LU", name: "Luxembourg" },
    { id: 94, code: "MG", name: "Madagascar" },
    { id: 95, code: "MW", name: "Malawi" },
    { id: 96, code: "MY", name: "Malaysia" },
    { id: 97, code: "MV", name: "Maldives" },
    { id: 98, code: "ML", name: "Mali" },
    { id: 99, code: "MT", name: "Malta" },
    { id: 100, code: "MR", name: "Mauritania" },
    { id: 101, code: "MU", name: "Mauritius" },
    { id: 102, code: "MX", name: "Mexico" },
    { id: 103, code: "MD", name: "Moldova" },
    { id: 104, code: "MN", name: "Mongolia" },
    { id: 105, code: "ME", name: "Montenegro" },
    { id: 106, code: "MA", name: "Morocco" },
    { id: 107, code: "MZ", name: "Mozambique" },
    { id: 108, code: "MM", name: "Myanmar" },
    { id: 109, code: "NA", name: "Namibia" },
    { id: 110, code: "NP", name: "Nepal" },
    { id: 111, code: "NL", name: "Netherlands" },
    { id: 112, code: "NZ", name: "New Zealand" },
    { id: 113, code: "NI", name: "Nicaragua" },
    { id: 114, code: "NE", name: "Niger" },
    { id: 115, code: "NG", name: "Nigeria" },
    { id: 116, code: "KP", name: "North Korea" },
    { id: 117, code: "NO", name: "Norway" },
    { id: 118, code: "OM", name: "Oman" },
    { id: 119, code: "PK", name: "Pakistan" },
    { id: 120, code: "PA", name: "Panama" },
    { id: 121, code: "PG", name: "Papua New Guinea" },
    { id: 122, code: "PY", name: "Paraguay" },
    { id: 123, code: "PE", name: "Peru" },
    { id: 124, code: "PH", name: "Philippines" },
    { id: 125, code: "PL", name: "Poland" },
    { id: 126, code: "PT", name: "Portugal" },
    { id: 127, code: "QA", name: "Qatar" },
    { id: 128, code: "RO", name: "Romania" },
    { id: 129, code: "RU", name: "Russia" },
    { id: 130, code: "RW", name: "Rwanda" },
    { id: 131, code: "SA", name: "Saudi Arabia" },
    { id: 132, code: "SN", name: "Senegal" },
    { id: 133, code: "RS", name: "Serbia" },
    { id: 134, code: "SL", name: "Sierra Leone" },
    { id: 135, code: "SG", name: "Singapore" },
    { id: 136, code: "SK", name: "Slovakia" },
    { id: 137, code: "SI", name: "Slovenia" },
    { id: 138, code: "SO", name: "Somalia" },
    { id: 139, code: "ZA", name: "South Africa" },
    { id: 140, code: "KR", name: "South Korea" },
    { id: 141, code: "ES", name: "Spain" },
    { id: 142, code: "LK", name: "Sri Lanka" },
    { id: 143, code: "SD", name: "Sudan" },
    { id: 144, code: "SE", name: "Sweden" },
    { id: 145, code: "CH", name: "Switzerland" },
    { id: 146, code: "SY", name: "Syria" },
    { id: 147, code: "TW", name: "Taiwan" },
    { id: 148, code: "TZ", name: "Tanzania" },
    { id: 149, code: "TH", name: "Thailand" },
    { id: 150, code: "TG", name: "Togo" },
    { id: 151, code: "TN", name: "Tunisia" },
    { id: 152, code: "TR", name: "Turkey" },
    { id: 153, code: "UG", name: "Uganda" },
    { id: 154, code: "UA", name: "Ukraine" },
    { id: 155, code: "AE", name: "United Arab Emirates" },
    { id: 156, code: "GB", name: "United Kingdom" },
    { id: 157, code: "US", name: "United States" },
    { id: 158, code: "UY", name: "Uruguay" },
    { id: 159, code: "UZ", name: "Uzbekistan" },
    { id: 160, code: "VE", name: "Venezuela" },
    { id: 161, code: "VN", name: "Vietnam" },
    { id: 162, code: "YE", name: "Yemen" },
    { id: 163, code: "ZM", name: "Zambia" },
    { id: 164, code: "ZW", name: "Zimbabwe" },
];